server:
  port: 2922

spring:
  application:
    name: xchat

#  redis:
#    port: 6379
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 10
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#    database: 0
#    timeout: 50000

  thymeleaf:
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html