server:
  port: 2922

spring:
  application:
    name: xchat

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aleestar.cn:3306/xchat?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: abc123

  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: aleestar.cn
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: abc123
    # 连接超时时间（毫秒）
    timeout: 6000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0

  thymeleaf:
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html

  mvc:
    static-path-pattern: /**
